apiVersion: v1
kind: PersistentVolume
metadata:
  name: jira-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Volumes/k8/jira
    type: Directory
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: psql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /Volumes/k8/psql
    type: Directory
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jira-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: psql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: jira
spec:
  serviceName: "jira-service"
  replicas: 1
  selector:
    matchLabels:
      app: jira
  template:
    metadata:
      labels:
        app: jira
    spec:
      containers:
      - name: jira
        image: divakar2201/microservices:jira
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "psql-service"
        - name: DB_PORT
          value: "5432"
        volumeMounts:
        - mountPath: /var/atlassian/application-data/jira
          name: jira-storage
  volumeClaimTemplates:
  - metadata:
      name: jira-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: jira-service
spec:
  type: NodePort
  selector:
    app: jira
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 30000
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: psql
spec:
  serviceName: "psql-service"
  replicas: 1
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - name: psql
        image: divakar2201/microservices:psql
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "jira"
        - name: POSTGRES_USER
          value: "jira"
        - name: POSTGRES_PASSWORD
          value: "jira"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: psql-storage
  volumeClaimTemplates:
  - metadata:
      name: psql-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: psql-service
spec:
  type: ClusterIP
  selector:
    app: psql
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jira-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: macmini.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: jira-service
            port:
              number: 8080