apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: portfolio-replicaset
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio-container
        image: divakar2201/microservices:portfolio
        ports:
        - containerPort: 1234

