apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: psql-replicaset
  labels:
    app: psql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: psql
  template:
    metadata:
      labels:
        app: psql
    spec:
      containers:
      - name: psql-container
        image: divakar2201/microservices:psql
        ports:
        - containerPort: 5432
